name: PR Tests
on:
  push:
    branches:
      - "**"
      - "!main"
  pull_request: {}
permissions: read-all
jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
      - name: Run Linters
        run: ./scripts/test.sh lint
  summary:
    name: Summary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
      - name: Create Summary
        run: ./scripts/test.sh summary
